name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install mlflow xgboost joblib

      - name: Run mlflow project
        run: |
          mlflow run MLProject

      - name: Install Python dependencies (post-run check)
        run: |
          pip show mlflow || pip install mlflow
          pip show xgboost || pip install xgboost

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | grep -Eo '[0-9a-f]{32}' | head -n 1)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Commit & Push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add mlruns/
          git commit -m "Upload artifact [skip ci]" || echo "No changes to commit"
          git push origin main