name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  train:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9"

      - name: Show debug info
        run: |
          python --version
          which python
          python -m pip --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install mlflow xgboost joblib

      - name: Run MLflow project
        run: |
          mlflow --version
          mlflow run . --env-manager virtualenv

      - name: Get latest MLflow run_id
        run: |
          set -e
          if [ -d mlruns/0 ]; then
            LATEST_DIR=$(ls -td mlruns/0/* | head -n 1)
            RUN_ID=$(basename "$LATEST_DIR")
            echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
            echo "Latest run_id: $RUN_ID"
          else
            echo "No mlruns/0 directory found"
            exit 1
          fi

      - name: Commit & Push results (mlruns/)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add mlruns/ || echo "no mlruns to add"
          git commit -m "Upload mlruns artifacts [skip ci]" || echo "No changes to commit"
          git push origin HEAD:$BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
